afia/urls.py
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('api-auth/',include('rest_framework.urls')),
    path('',include('main.urls')),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__',include(debug_toolbar.urls)),
    ] + urlpatterns

main/urls.py
from django.urls import path,include
from django.views.generic import TemplateView,DetailView
from django.contrib.auth import views as auth_views
from main import forms
from main import views
from main import models
from rest_framework import routers
from main import endpoints
from main import admin

router = routers.DefaultRouter()
router.register(r'Orderlines',endpoints.PaidOrderLineViewSet)
router.register(r'Order',endpoints.PaidOrderViewSet)

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='main/login.html',form_class=forms.AuthenticationForm,),name='login',),
    path('signup/',views.SignupView.as_view(),name='signup'),
    path('address/',views.AddressListView.as_view(),name='address_list'),
    path('address/create/',views.AddressCreateView.as_view(),name='address_create'),
    path('address/<int:pk>/',views.AddressUpdateView.as_view(),name='address_update'),
    path('address/<int:pk>/delete/',views.AddressDeleteView.as_view(),name='address_delete'),
    path('products/<slug:tag>/',views.ProductListView.as_view(),name='products',),
    path('product/<slug:slug>/', DetailView.as_view(model=models.Product),name='product',),
    path('add_to_basket/',views.add_to_basket,name='add_to_basket',),
    path('basket/',views.manage_basket,name='basket'),
    path('order/done/',TemplateView.as_view(template_name='main/order_done.html'),name='checkout_done',),
    path('order/address_select/',views.AddressSelectionView.as_view(),name='address_select',),
    path('about-us/',TemplateView.as_view(template_name='main/about_us.html'),name='about_us'),
    path('contact-us/',views.ContactUsView.as_view(),name='contact_us'),
    path('',TemplateView.as_view(template_name='main/home.html'),name='home'),
    path('order-dashboard/', views.OrderView.as_view(),name='order_dashboard',),
    path('api/',include(router.urls)),
    path('admin/',admin.main_admin.urls),
    path('office-admin',admin.central_office_admin.urls),
    path('dispatch-admin',admin.dispatchers_admin.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.core.validators import MinValueValidator
import logging
from . import exceptions

logger = logging.getLogger(__name__)


class UserManager(BaseUserManager):
    use_in_migrations = True
    def _create_user(self,email,password,**extra_fields):
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email,**extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self,email,password=None, **extra_fields):
        extra_fields.setdefault("is_staff",False)
        extra_fields.setdefault("is_superuser",False)
        return self._create_user(email,password,**extra_fields)

    def create_superuser(self,email,password,**extra_fields):
        extra_fields.setdefault('is_staff',True)
        extra_fields.setdefault("is_superuser",True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("superuser must have is_superuser=True")
        return self._create_user(email,password,**extra_fields)

class User(AbstractUser):
    username = None
    email =models.EmailField('email address',unique=True)
    USERNAME_FIELD ='email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    @property
    def is_employee(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Employees").exists())

    @property
    def is_dispatcher(self):
        return self.is_active and (self.is_superuser or self.is_staff and self.groups.filter(name="Dispatchers").exists())

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)


class Address(models.Model):
    SUPPORTED_COUNTRIES = (
        ("uk","United Kingdom"),("us","United states of America"),("ng","Nigeria"),
    )
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    address1 = models.CharField("Address line 1",max_length=60)
    address2 = models.CharField("Address line 2",max_length=60,blank=True)
    zip_code = models.CharField('ZIP / Postal code',max_length=12)
    city = models.CharField(max_length=60)
    country = models.CharField(max_length=3,choices=SUPPORTED_COUNTRIES)

    def __str__(self):
        return ", ".join([self.name,self.address1,self.address2,self.zip_code,self.city,self.country])

class Product(models.Model):

    objects = ActiveManager()
    tags = models.ManyToManyField('ProductTag',blank=True)
    name = models.CharField(max_length=32)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=6,decimal_places=2)
    slug = models.SlugField(max_length=48)
    active = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product-images')
    thumbnail = models.ImageField(upload_to='product-thumbnails',null=True)

    def __str__(self):
        return self.product.name

class ProductTagManager(models.Manager):
    def get_by_natural_key(self,slug):
        return self.get(slug=slug)

class ProductTag(models.Model):
    objects = ProductTagManager()
    name = models.CharField(max_length=32)
    slug = models.SlugField(max_length=48)
    description = models.TextField(blank=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    
    def natural_key(self):
        return (self.slug,)

class Order(models.Model):
    NEW = 10
    PAID =20
    DONE =30
    STATUSES=((NEW,"New"),(PAID,'Paid'),(DONE,'Done'))
   
    user = models.ForeignKey(User,models.CASCADE)
    status = models.IntegerField(choices=STATUSES,default=NEW)
    billing_name = models.CharField(max_length=60)
    billing_address1 = models.CharField(max_length=60)
    billing_address2 = models.CharField(max_length=60, blank=True)
    billing_zip_code =models.CharField(max_length=12)
    billing_city = models.CharField(max_length=60)
    billing_country = models.CharField(max_length=3)
    shipping_name = models.CharField(max_length=60)
    shipping_address1 = models.CharField(max_length=60)
    shipping_address2 = models.CharField(max_length=60, blank=True)
    shipping_zip_code =models.CharField(max_length=12)
    shipping_city = models.CharField(max_length=60)
    shipping_country = models.CharField(max_length=3)
    date_updated = models.DateTimeField(auto_now=True)
    date_added = models.DateTimeField(auto_now_add=True)


class OrderLine(models.Model):
    NEW = 10
    PROCESSING = 20
    SENT = 30
    CANCELLED = 40
    STATUSES = ((NEW,'New'),(PROCESSING,'Processing'),(SENT,'Sent'),(CANCELLED,'Cancelled'))

    order = models.ForeignKey(Order,models.CASCADE,related_name='lines')
    product = models.ForeignKey(Product,models.PROTECT)
    status = models.IntegerField(choices=STATUSES,default=NEW)

class Basket(models.Model):
    OPEN = 10
    SUBMITTED = 20
    STATUSES = ((OPEN,"Open"),(SUBMITTED,"Submitted"))
    user = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    status = models.IntegerField(choices=STATUSES,default=OPEN)
    
    
    def is_empty(self):
        return self.basketline_set.all().count() == 0

    def count(self):
        return sum(i.quantity for i in self.basketline_set.all())

    def create_order(self,billing_address,shipping_address):

        if not self.user:
            raise  exceptions.BasketException("Cannot create order without user.")
        logger.info("Creating order for basket_id=%d"", shipping_address_id=%d, billing_address_id=%d",
        self.id,billing_address.id,shipping_address.id,)
        order_data = {
            "user":self.user,
            "billing_name": billing_address.name,
            "billing_address1":billing_address.address1,
            "billing_address2": billing_address.address2,
            "billing_zip_code": billing_address.zip_code,
            "billing_city": billing_address.city,
            "billing_country": billing_address.country,
            "shipping_name": shipping_address.name,
            "shipping_address1": shipping_address.address1,
            "shipping_address2": shipping_address.address2,
            "shipping_zip_code": shipping_address.zip_code,
            "shipping_city": shipping_address.city,
            "shipping_country": shipping_address.country,
            }
        order = Order.objects.create(**order_data)
        c=0
        for line in self.basketline_set.all():
            for item in range(line.quantity):
                order_line_data = {
                    "order":order,
                    "product":line.product,
                }
                order_line = OrderLine.objects.create(**order_line_data)
                c +=1
        logger.info("Created order with id=%d and lines_count=%d",order.id,c,)
        self.status = Basket.SUBMITTED
        self.save()
        return order


class BasketLine(models.Model):
    basket = models.ForeignKey(Basket,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1,validators=[MinValueValidator(1)])

main/views.py
from django.views.generic.edit import FormView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import (LoginRequiredMixin,UserPassesTestMixin)
from django import forms as django_forms
from django.db import models as django_models
import django_filters
from django_filters.views import FilterView
from main import forms
from django.urls import reverse,reverse_lazy
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404,render
from main import models
import logging
from django.contrib.auth import login,authenticate
from django.contrib import messages
from django.http import HttpResponseRedirect


logger = logging.getLogger('__name__')


class SignupView(FormView):
    template_name='main/signup.html'
    form_class = forms.UserCreationForm

    def get_success_url(self):
        redirect_to = self.request.GET.get("next",'/')
        return redirect_to

    def form_valid(self,form):
        response = super().form_valid(form)
        form.save()
        email =form.cleaned_data.get('email')
        raw_password =form.cleaned_data.get('password1')
        logger.info('New signup for email=%s through SignupView',email)
        user = authenticate(email=email,password=raw_password)
        login(self.request,user)
        form.send_mail()
        messages.info(self.request,'You signed up successfully.')
        return response


class AddressListView(LoginRequiredMixin,ListView):
    model = models.Address

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressCreateView(LoginRequiredMixin,CreateView):
    model = models.Address
    fields = [ "name","address1","address2","zip_code","city","country",]
    success_url = reverse_lazy('address_list')

    def form_valid(self,form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)

class AddressUpdateView(LoginRequiredMixin,UpdateView):
    model = models.Address
    fields = [ "name","address1","address2","zip_code","city","country",]
    success_url = reverse_lazy('address_list')

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddressDeleteView(LoginRequiredMixin,DeleteView):
    model = models.Address
    success_url = reverse_lazy('address_list')

    def get_queryset(self):
       return  self.model.objects.filter(user=self.request.user)
    
class ContactUsView(FormView):
    template_name = 'main/contact_form.html'
    form_class = forms.ContactForm
    success_url = '/'


    def form_valid(self,form):
        form.send_mail()
        return super().form_valid(form)


class ProductListView(ListView):
    template_name = "main/product_list.html"
    paginate_by = 4

    def get_queryset(self):
        tag = self.kwargs['tag']
        self.tag = None
        if tag != 'all':
            self.tag = get_object_or_404(models.ProductTag,slug=tag)
        if self.tag:
            products = models.Product.objects.active().filter(tags=self.tag)
        else:
            products = models.Product.objects.active()
        return products.order_by('name')    


def add_to_basket(request):
    product = get_object_or_404(
        models.Product, pk=request.GET.get("product_id")
    )
    basket = request.basket
    if not request.basket:
        if request.user.is_authenticated:
            user = request.user
        else:
            user = None
        basket = models.Basket.objects.create(user=user)
        request.session["basket_id"] = basket.id

    basketline, created = models.BasketLine.objects.get_or_create(
        basket=basket, product=product
    )
    if not created:
        basketline.quantity += 1
        basketline.save()
    return HttpResponseRedirect(
        reverse("product", args=(product.slug,))
    )


def manage_basket(request):
    if not request.basket:
        return render(request, "main/basket.html", {"formset": None})

    if request.method == "POST":
        formset = forms.BasketLineFormSet(
            request.POST, instance=request.basket
        )
        if formset.is_valid():
            formset.save()
    else:
        formset = forms.BasketLineFormSet(
            instance=request.basket
        )

    if request.basket.is_empty():
        return render(request, "main/basket.html", {"formset": None})

    return render(request, "main/basket.html", {"formset": formset})


class AddressSelectionView(LoginRequiredMixin, FormView):
    template_name = "main/address_select.html"
    form_class = forms.AddressSelectionForm
    success_url = reverse_lazy("checkout_done")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        del self.request.session["basket_id"]
        basket = self.request.basket
        basket.create_order(
            form.cleaned_data["billing_address"],
            form.cleaned_data["shipping_address"],
        )
        return super().form_valid(form)


class DateInput(django_forms.DateInput):
    input_type = "date"


class OrderFilter(django_filters.FilterSet):
    class Meta:
        model = models.Order
        fields = {
            "user__email": ["icontains"],
            "status": ["exact"],
            "date_updated": ["gt", "lt"],
            "date_added": ["gt", "lt"],
        }
        filter_overrides = {
            django_models.DateTimeField: {
                "filter_class": django_filters.DateFilter,
                "extra": lambda f: {"widget": DateInput},
            }
        }


class OrderView(UserPassesTestMixin, FilterView):
    filterset_class = OrderFilter
    login_url = reverse_lazy("login")

    def test_func(self):
        return self.request.user.is_staff == True

main/templates/main/address_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}

<h2>Delete Address</h2>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete it?</p>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/address_form.html
{% extends 'main/base.html' %}

{% block content %}

<h2>Add a new address</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/address_select.html
{% extends 'main/base.html' %}

{% block content %}
<h2>Select the billing/shipping addresses</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
    <a href="{% url 'address_create' %}" class="btn btn-primary">Add a new one</a>
</form>
{% endblock content %}

main/templates/main/address_update.html
{% extends 'main/base.html' %}

{% block content %}

<h2>Add a new address</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Hello,World!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg- light"> <a class="navbar-brand" href="/">Afia</a> <button
            class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"> <span
                class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == '/' %} active {% endif %}"> <a class="nav-link"
                        href="/">Home</a> </li>
                <li class="nav-item  {% if request.path == '/about-us/' %} active {% endif %}"> <a class="nav-link"
                        href="about-us/">About us</a> </li>
            </ul>
        </div>
    </nav>
    {% if request.basket %}
    <div>
        {{ request.basket.count}}
        items in basket
    </div>
    {% endif %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% block content %}
    {% endblock content %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block js %}
    {% endblock js %}
</body>

</html>

main/templates/main/basket.html
{% extends 'main/base.html' %}

{% block content %}

<h2>Basket</h2>
{% if formset %}
<p>You can adjust the quantities below.</p>
<form method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
    <p>
        {{form.instance.product.name}}
        {{form}}
    </p>
    {% endfor %}
    <button type="submit" class="btn btn-default">Update basket</button>
    {% if user.is_authenticated %}
    <a href="{% url 'address_select' %}" class="btn btn-primary">Place order</a>
    {% else %}
    <a href="{% url 'signup' %}?next={% url 'address_select' %}" class="btn btn-primary">Signup</a>
    <a href="{% url 'login' %}?next={% url 'address_select' %}" class="btn btn-primary">Login</a>
    {% endif %}
</form>
{% else %}
<p>You have no items in the basket</p>
{% endif %}
{% endblock content %}

{% block js %}
{% if formset %}
{{ formset.media }}
{% endif %}
{% endblock js %}

main/templates/main/invoice.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Invoice</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h1>Afia</h1>
                <h2>Invoice</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-8">
                Invoice Number BT{{order.id}}
                <br />
                Date:
                {{ order.date_added|date}}
            </div>
            <div class="col-4">
                {{ order.billing_name }}<br />
                {{ order.billing_address1 }}<br />
                {{ order.billing_address2 }}<br />
                {{ order.billing_zip_code }}<br />
                {{ order.billing_city }}<br />
                {{ order.billing_country }}<br />
            </div>
        </div>
        <div class="row">
            <div class="col">
                <table class="table" style="width: 95%; margin: 50px 0px 50px 0px">
                    <tr>
                        <th>Product Name</th>
                        <th>Price</th>
                    </tr>
                    {% for line in order.line.all %}
                    <tr>
                        <td>{{ line.product.name}}</td>
                        <td>{{ line.product.price}}</td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <p>
                    Please pay within 30days
                </p>
                <p>
                    Afia inc.
                </p>
            </div>
        </div>
    </div>

</body>

</html>

main/templates/main/most_bought_products.html
{% extends 'admin/base_site.html' %}
{% load static %}
{% block extrahead %}
<script src="{% static 'js/Chart.bundle.min.js' %}"></script>
{% endblock extrahead %}
{% block content %}
<p>
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Set period" />
</form>
</p>
{% if labels and values %}
<canvas id="myChart" width="900" height="400"></canvas>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: {{ labels| safe }},
    datasets: [
        {
            label: 'No of purchases',
            backgroundColor: 'blue',
            data: {{ values| safe }}
            }
    ]
        },
    options: {
        responsive: false,
            scales: {
            yAxes: [
                {
                    ticks: {
                        beginAtZero: true
                    }
                }
            ]
        }
    }
      });
</script>
{% endif %}
{% endblock content %}

main/templates/main/order_done.html
{% extends 'main/base.html' %}

{% block content %}
<p>Thanks for your order.</p>
{% endblock content %}

main/templates/main/order_filter.html
{% extends 'main/base.html' %}
{% load render_table from django_tables2 %}

{% block content %}
<h2>Order dashboard</h2>
<form method="get">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
<p>
    {% render_table filter.qs %}
</p>
{% endblock content %}

main/templates/main/orders_per_day.html
{% extends "admin/base_site.html" %}
{% load static %}
{% block extrahead %}
<script src="{% static 'js/Chart.bundle.min.js' %}"></script>
{% endblock extrahead %}
{% block content %}

<canvas id="myChart" width="900" height="400"></canvas>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: {{ labels| safe }},
    datasets: [
        {
            label: 'No of orders',
            backgroundColor: 'blue',
            data: {{ values| safe }}
          }
    ]
      },
    options: {
        responsive: false,
            scales: {
            yAxes: [
                {
                    ticks: {
                        beginAtZero: true
                    }
                }
            ]
        }
    }
    });
</script>
{% endblock content %}

main/templates/main/product_detail.html
{% extends "main/base.html" %}
{% load render_bundle from webpack_loader %}

{% block content %}
<h1>products</h1>
<table class="table">
    <tr>
        <th>Name</th>
        <td>{{ object.name }}</td>
    </tr>
    <tr>
        <th>Cover images</th>
        <td>
            <div id="imagebox">
                Loading...
            </div>
        </td>
    </tr>
    <tr>
        <th>Price</th>
        <td>{{ object.price }}</td>
    </tr>
    <tr>
        <th>Description</th>
        <td>{{ object.description|linebreaks }}</td>
    </tr>
    <tr>
        <th>Tags</th>
        <td>{{ object.tags.all|join:","|default:"No tags available" }}</td>
    </tr>
    <tr>
        <th>In stock</th>
        <td>{{ object.in_stock|yesno|capfirst }}</td>
    </tr>
    <tr>
        <th>Updated</th>
        <td>{{ object.date_updated|date:"F Y" }}</td>
    </tr>
</table>
<a href="{% url "add_to_basket" %}?product_id={{ object.id }}">Add to basket</a>
{% endblock content %}

{% block js %}
{% render_bundle 'imageswitcher' 'js' %}
<script>
    document.addEventListener("DOMContentLoaded", function (event) {
        var images = [
            {% for image in object.productimage_set.all %}
          {
            "image": "{{ image.image.url|safe }}",
            "thumbnail": "{{ image.thumbnail.url|safe }}"
        },
        {% endfor %}
      ]
        ReactDOM.render(React.createElement(ImageBox, {
            images: images,
            imageStart: images[0]
        }), document.getElementById('imagebox'));
    });
</script>
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}

{% block content %}

<h1>Products</h1>
{% for product in page_obj %}
<p>{{ product.name }}</p>
<p><a href="{% url 'product' product.slug %}">See it here</a></p>
{% if not forloop.last %}
<hr>
{% endif %}
{% endfor %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="?page={{ page_obj.previouse_page_number }}" class="page-link">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link">Previous</a>
        </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %} active{% endif %}">
            <a href="?page={{ pagenum }}" class="page-link">{{pagenum}}</a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="?page={{ page_obj.next_page_number }}" class="page-link">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a href="#" class="page-link">Next</a>
        </li>
        {% endif %}

    </ul>
</nav>
{% endblock content %}

main/templates/main/signup.html
{% extends 'main/base.html' %}

{% block content %}

<h2>Sign Up</h2>
<p>Please fill the form below.</p>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        {{ form.email.label_tag }}
        <input type="email" class="form-control{% if form.email.errors %} is-invalid {% endif %}" id="id_email"
            name="email" placeholder="Your email" value="{{ form.email.value|default:''}}">
        {% if form.email.errors %}
        <div class="invalid-feedback">
            {{ form.email.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password1.label_tag }}
        <input type="password" name="password1" id="id_password1"
            class="form-control {% if form.password1.errors %}is_invalid{% endif %}"
            value="{{ form.password1.value|default:''}}">
        {% if form.password1.errors %}
        <div class="invalid_feedback">
            {{ form.password1.errors }}
        </div>
        {% endif %}
    </div>
    <div class="form-group">
        {{ form.password2.label_tag }}
        <input type="password" name="password2" id="id_password2"
            class="form-control {% if form.password2.errors %}is_invalid{% endif %}"
            value="{{ form.password2.value|default:''}}">
        {% if form.password2.errors %}
        <div class="invalid_feedback">
            {{ form.password2.errors }}
        </div>
        {% endif %}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock content %}